spring:
  application:
    name: weshopify-platform-service-registry

server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: ${REGISTRY_HOST_NAME:localhost}
    prefer-ip-address: true
    

  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  
  tracing: 
     sampling: 
        probability: 1.0

logging:
   pattern: 
     level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
